server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/orderFallback
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - TokenRelay
            - name: CircuitBreaker
              args:
                name: inventoryService
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/master
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8080}/realms/master/protocol/openid-connect/certs

  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,tracing
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"