# Discovery Server (Eureka)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans" # تأكد من اسم خدمة zipkin لديك
            - name: MANAGEMENT_TRACING_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8761