apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      # ننتظر حتى يعمل Kafka أولاً
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;' ]
      containers:
        - name: notification-service
          image: notification-service:v1
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: microservices-config
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092" # إضافة صريحة لضمان القيمة