spring.application.name=discovery-server
server.port=8761
# 1. Config Server Connection
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
spring.cloud.config.username=admin
spring.cloud.config.password=admin
# 2. Eureka Server Specific Settings
# إخبار يوريكا أنه هو السيرفر ولا يحتاج لتسجيل نفسه لدى أحد
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.hostname=discovery-server
# 3. Observability & Tracing
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.health.show-details=always
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.metrics.tags.application=${spring.application.name}
# 4. Security (Keycloak for Dashboard protection if needed)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/master/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master
spring.security.user.name=admin
spring.security.user.password=admin