spring.application.name=inventory-service
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true
server.port=8081
# Eureka Configuration (Unified)
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
# Security Configuration (Internal DNS for Kubernetes)
# استبدل localhost باسم الخدمة داخل الكلاستر لضمان تواصل الـ Containers
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/master/protocol/openid-connect/certs
# Observability
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
# Database (استخدم اسم السيرفس في الدوكر لسهولة النشر)
spring.datasource.url=jdbc:mysql://host.docker.internal:3307/inventory_service
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
