spring.application.name=inventory-service
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.fail-fast=true
server.port=8081

# Eureka Configuration (Unified)
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Security Configuration (Internal DNS for Kubernetes)
# Replace localhost with service name inside the cluster to ensure container communication
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_URL:http://localhost:8080}/realms/master/protocol/openid-connect/certs

# Observability
management.endpoints.web.exposure.include=health,info,prometheus,tracing
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

 Database Configuration
# The system will look for DB_HOST, and if not found, will consider it localhost by default
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3307/inventory_service
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update

# Use IP address instead of hostname
eureka.instance.prefer-ip-address=true

# Hostname configuration
eureka.instance.hostname=localhost

