package org.example.notificationservice.event;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Event representing a successfully placed order in the e-commerce system.
 * This event is published to Kafka and consumed by the notification service
 * to trigger customer notifications via email or other channels.
 *
 * <p>The no-argument constructor is required for JSON deserialization
 * when consuming messages from Kafka topics.</p>
 *
 * @author Notification Service Team
 * @version 1.0
 * @since 2024
 */
@Data
@AllArgsConstructor
@NoArgsConstructor // Required for JSON deserialization in Kafka message consumption
public class OrderPlacedEvent {
    /**
     * The unique order number generated by the order service.
     * Used as a reference for tracking and customer communication.
     */
    private String orderNumber;
}