server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # The path where .properties files for all services will be placed inside the container
          search-locations: file:/app/config-repo
      fail-fast: true  # Fail quickly if Config Server is unreachable
      retry:
        max-attempts: 20      # Number of retry attempts
        initial-interval: 3000  # Initial retry interval in milliseconds (3 seconds)

# Eureka settings for registration
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
