server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # المسار الذي ستوضع فيه ملفات الـ .properties لكل الخدمات داخل الحاوية
          search-locations: file:/app/config-repo

# إعدادات يوريكا للتسجيل
eureka:
  instance:
    hostname: config-server
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/

# المراقبة
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}